import { NoxionPlugin, BlogPost } from '@noxion/types'

export interface SEOConfig {
  generateMetaTags: boolean
  enableOpenGraph: boolean
  enableTwitterCards: boolean
  enableJsonLd: boolean
  defaultImage: string
  siteName: string
  twitterHandle?: string
  facebookAppId?: string
  autoGenerateDescriptions: boolean
  maxDescriptionLength: number
  keywords: string[]
}

export const createSEOPlugin = (config: Partial<SEOConfig> = {}): NoxionPlugin => {
  const defaultConfig: SEOConfig = {
    generateMetaTags: true,
    enableOpenGraph: true,
    enableTwitterCards: true,
    enableJsonLd: true,
    defaultImage: '/og-default.jpg',
    siteName: 'Noxion Blog',
    autoGenerateDescriptions: true,
    maxDescriptionLength: 160,
    keywords: ['blog', 'noxion', 'cms'],
    ...config
  }

  return {
    name: 'seo-optimizer',
    version: '2.1.0',
    description: 'Comprehensive SEO optimization plugin with meta tags, Open Graph, and structured data',
    author: 'Noxion Team',
    dependencies: ['analytics'], // Depends on analytics for tracking
    config: defaultConfig,
    
    async register(context) {
      console.log('Registering SEO Plugin with config:', defaultConfig)
      
      // Hook into post rendering to add SEO metadata
      context.registerHook('afterPostRender', async (post: BlogPost) => {
        const enhancedPost = await enhancePostWithSEO(post, defaultConfig)
        
        if (defaultConfig.generateMetaTags) {
          console.log('SEO: Meta tags generated for', post.slug)
        }
        
        return enhancedPost
      })
      
      // Hook into posts query to optimize list pages
      context.registerHook('afterPostsQuery', async (posts: BlogPost[]) => {
        return posts.map(post => generateListPageSEO(post, defaultConfig))
      })
      
      // Register SEO components
      context.registerComponent('SEOHead', createSEOHeadComponent(defaultConfig))
      
      context.registerComponent('StructuredData', createStructuredDataComponent(defaultConfig))
      
      context.registerComponent('SEOAnalytics', createSEOAnalyticsComponent(defaultConfig))
    }
  }
}

async function enhancePostWithSEO(post: BlogPost, config: SEOConfig): Promise<BlogPost> {
  const seoData = {
    title: generateSEOTitle(post.title, config),
    description: generateSEODescription(post, config),
    keywords: [...config.keywords, ...extractKeywords(post)],
    image: post.cover || config.defaultImage,
    url: `/articles/${post.slug}`,
    publishedTime: post.createdAt,
    modifiedTime: post.updatedAt,
    author: post.author || 'Noxion Team',
  }
  
  return {
    ...post,
    seo: seoData
  }
}

function generateListPageSEO(post: BlogPost, config: SEOConfig): BlogPost {
  return {
    ...post,
    listSeo: {
      snippet: generateSEODescription(post, config, 120), // Shorter for lists
      image: post.cover || config.defaultImage
    }
  }
}

function generateSEOTitle(title: string, config: SEOConfig): string {
  if (title.includes(config.siteName)) {
    return title
  }
  return `${title} | ${config.siteName}`
}

function generateSEODescription(post: BlogPost, config: SEOConfig, maxLength?: number): string {
  const length = maxLength || config.maxDescriptionLength
  
  if (post.description && post.description.length <= length) {
    return post.description
  }
  
  if (config.autoGenerateDescriptions && post.content) {
    // Extract first paragraph and truncate
    const firstParagraph = post.content.split('\n\n')[0]
    const cleanText = firstParagraph.replace(/[#*`]/g, '').trim()
    
    if (cleanText.length <= length) {
      return cleanText
    }
    
    return cleanText.substring(0, length - 3) + '...'
  }
  
  return post.description || `Read more about ${post.title} on ${config.siteName}`
}

function extractKeywords(post: BlogPost): string[] {
  // Simple keyword extraction from title and content
  const text = `${post.title} ${post.content || ''}`.toLowerCase()
  const words = text.match(/\b\w{4,}\b/g) || []
  
  // Count word frequency and return top keywords
  const frequency: Record<string, number> = {}
  words.forEach(word => {
    frequency[word] = (frequency[word] || 0) + 1
  })
  
  return Object.entries(frequency)
    .sort(([,a], [,b]) => b - a)
    .slice(0, 5)
    .map(([word]) => word)
}

function createSEOHeadComponent(config: SEOConfig): any {
  return function SEOHead({ post }: { post?: BlogPost }) {
    if (!post?.seo) return null
    
    const { seo } = post
    const metaTags = []
    
    if (config.generateMetaTags) {
      metaTags.push(
        { name: 'description', content: seo.description },
        { name: 'keywords', content: seo.keywords.join(', ') },
        { name: 'author', content: seo.author }
      )
    }
    
    if (config.enableOpenGraph) {
      metaTags.push(
        { property: 'og:title', content: seo.title },
        { property: 'og:description', content: seo.description },
        { property: 'og:image', content: seo.image },
        { property: 'og:url', content: seo.url },
        { property: 'og:type', content: 'article' },
        { property: 'og:site_name', content: config.siteName }
      )
      
      if (config.facebookAppId) {
        metaTags.push({ property: 'fb:app_id', content: config.facebookAppId })
      }
    }
    
    if (config.enableTwitterCards) {
      metaTags.push(
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: seo.title },
        { name: 'twitter:description', content: seo.description },
        { name: 'twitter:image', content: seo.image }
      )
      
      if (config.twitterHandle) {
        metaTags.push({ name: 'twitter:site', content: config.twitterHandle })
      }
    }
    
    return {
      type: 'head',
      props: {
        children: metaTags.map((tag, index) => ({
          type: 'meta',
          key: index,
          props: tag
        }))
      }
    }
  }
}

function createStructuredDataComponent(config: SEOConfig): any {
  return function StructuredData({ post }: { post?: BlogPost }) {
    if (!post?.seo || !config.enableJsonLd) return null
    
    const { seo } = post
    const structuredData = {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: seo.title,
      description: seo.description,
      image: seo.image,
      url: seo.url,
      datePublished: seo.publishedTime,
      dateModified: seo.modifiedTime,
      author: {
        '@type': 'Person',
        name: seo.author
      },
      publisher: {
        '@type': 'Organization',
        name: config.siteName
      }
    }
    
    return {
      type: 'script',
      props: {
        type: 'application/ld+json',
        dangerouslySetInnerHTML: {
          __html: JSON.stringify(structuredData)
        }
      }
    }
  }
}

function createSEOAnalyticsComponent(config: SEOConfig): any {
  return function SEOAnalytics() {
    return {
      type: 'div',
      props: {
        className: 'seo-analytics p-4 border rounded',
        children: [
          {
            type: 'h3',
            props: { children: 'SEO Status' }
          },
          {
            type: 'ul',
            props: {
              children: [
                { type: 'li', props: { children: `Meta Tags: ${config.generateMetaTags ? '✅' : '❌'}` }},
                { type: 'li', props: { children: `Open Graph: ${config.enableOpenGraph ? '✅' : '❌'}` }},
                { type: 'li', props: { children: `Twitter Cards: ${config.enableTwitterCards ? '✅' : '❌'}` }},
                { type: 'li', props: { children: `Structured Data: ${config.enableJsonLd ? '✅' : '❌'}` }},
                { type: 'li', props: { children: `Auto Descriptions: ${config.autoGenerateDescriptions ? '✅' : '❌'}` }}
              ]
            }
          }
        ]
      }
    }
  }
}

export default createSEOPlugin